### ISSUE TITLE
Change phrasing of system notification

### ISSUE THREAD

**Issue by yannxaver** [Inversil/LESosx#1]
When you press Shift+CMD+1, it displays 'LES Paused' or 'LES Unpaused'.

I installed LES quite a while ago and forgot about it. When I used the same keyboard shortcut in VSCode today, this notification kept showing up. I had no idea what LES means and Google also didn't show any results.

It took me quite a long time to figure out that this was the Live Enhancement Suite. 
Please change the phrasing from LES to Live Enhancement Suite to avoid this confusion. I tried creating a pull request but have no edit rights.

**Comment by Inversil** [comment]
Hey!
I'm so sorry you had this experience. I'm not super familiar with GitHub, how do I give everyone permission to make pull requests?

**Comment by yannxaver** [comment]
No worries about it. It's still a great tool that you have created! 

You would have to make me a collaborator I think. If you want to incorporate these changes, it might be easier to just update it yourself, since it's just two lines of code.
